# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ifdef
version:      0.05
version_from: lib/ifdef.pm
installdirs:  site
requires:
    Filter::Util::Call:            0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
